apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prd-internal
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 "hello it's Charles\n";
            add_header Content-Type text/plain;
        }
    }
