apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MacTynow/curly-octo-doodle.git
    targetRevision: prd
    path: argocd/manifests/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: prd-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
